# Generated by Django 3.1.5 on 2021-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2gis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coord',
            name='public',
        ),
        migrations.AddField(
            model_name='path',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Публичный'),
        ),
        migrations.AlterField(
            model_name='typecoord',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
