# Generated by Django 3.1.5 on 2021-01-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_2gis', '0002_auto_20210118_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='coord',
            name='city',
            field=models.CharField(default='Псков', max_length=255, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
